// Auto-generated by OpenLane
module counter_dut(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input enable,
  input up_down,
  output[3:0] counter
);
endmodule
